name = "tool-web"
# type = "typescript"  # 或者 "typescript" 根据你使用的语言类型

# D1 数据库配置 仅用以本地调试，线上走pages绑定的db
[[d1_databases]]
binding = "DB"
database_name = "yifang-tool"
database_id = "afdabfae-6edd-4def-8e77-6a1171009b9c"

# d1数据库需要在pages的设置->绑定->D1数据库（变量名称为DB，数据库为创建的d1数据库）

# 本地调试指定线上数据库 wrangler pages dev --local --d1 yifang-tool:afdabfae-6edd-4def-8e77-6a1171009b9c
# 本地调试的话  也需要在本地建表：
#  notes表： wrangler d1 execute yifang-tool --command="CREATE TABLE notes (id TEXT PRIMARY KEY,uid TEXT NOT NULL,title TEXT NOT NULL,content TEXT NOT NULL,create_time DATETIME DEFAULT CURRENT_TIMESTAMP,update_time DATETIME DEFAULT CURRENT_TIMESTAMP);"
#  user表：wrangler d1 execute yifang-tool --command="CREATE TABLE user ("id" text PRIMARY KEY,"email" text,"avatar" text,"created_at" text,"last_login" text, third_party_uid TEXT, username TEXT, user_level INTEGER DEFAULT 0, third_party_type TEXT)"
#  简历表：wrangler d1 execute yifang-tool --command="CREATE TABLE resumes (     id TEXT PRIMARY KEY,     uid TEXT NOT NULL,     name TEXT NOT NULL,     template TEXT DEFAULT 'modern',     personal_info TEXT,     work_experience TEXT,     education TEXT,     skills TEXT,     projects TEXT,     certificates TEXT,     others TEXT,     create_time DATETIME DEFAULT CURRENT_TIMESTAMP,     update_time DATETIME DEFAULT CURRENT_TIMESTAMP )"
#  公司对比表：：wrangler d1 execute yifang-tool --command="CREATE TABLE companies (   id TEXT PRIMARY KEY,   uid TEXT NOT NULL,   name TEXT NOT NULL,   position TEXT NOT NULL,   salary TEXT,   benefits TEXT,   work_days TEXT,   work_hours TEXT,   location TEXT,   welfare TEXT,   overtime TEXT,   leave_policy TEXT,   notes TEXT,   create_time DATETIME DEFAULT CURRENT_TIMESTAMP,   update_time DATETIME DEFAULT CURRENT_TIMESTAMP )"

# 使用该命令查看本地有哪些表：wrangler d1 execute yifang-tool --command="SELECT name FROM sqlite_master WHERE type='table';"

# 本地启动调试服务：wrangler pages dev .
# 本地调试设置环境变量（线上的环境变量是绑定在pages的变量和机密里）：
[vars]
JWT_SECRET = "6197upXX81DUXMF9I8f@IqVOi3NEYYR@FBTDmyMf1mY5A4ExMiiTz2!hr%5tpPZfXE^d^"
LINUXDO_CLIENT_ID = "ndZjdtb3uuqsdQsLXVP9EryepP4g9p1C"
LINUXDO_CLIENT_SECRET = "tPD2IZxu5SeG9HfoF3CkwVc3CrllVQXt"
# QQ登录配置（已隐藏）
QQ_CLIENT_ID = "102806259"
QQ_REDIRECT_URI1 = "http://127.0.0.1:8788/qq-auth"
QQ_REDIRECT_URI = "https://tool.fologde.com/qq-auth"
# Gitee登录配置
GITEE_CLIENT_ID = "a33bfc0232834f1fd309dc2c1696821bc821e5f746ef28869496d88fb7b4b104"
GITEE_CLIENT_SECRET = "667d2c96eed94a91b4cd5542a408d719817071b2b8800b45abd8cc0b87eaa16c"
GITEE_REDIRECT_URI = "http://127.0.0.1:8788/gitee-auth"
# Github登录配置
GITHUB_CLIENT_ID = "Ov23lih4DozBgCiAwLWe"
GITHUB_CLIENT_SECRET = "6d47d057db84d7f6b7b82a59c54a5fc54d89f327"
GITHUB_REDIRECT_URI = "http://127.0.0.1:8788/github-auth"