/**
 * 每条路由的 SEO 优化标题（不含站名后缀，展示时会拼上 " | 一方工具箱"）。
 *
 * 使用方：
 *  - src/router/index.ts afterEach：SPA 内导航时 document.title（用户标签页标题与爬虫一致）
 *  - scripts/generate-page-meta.mjs：生成 functions/_page-meta.js，
 *    供预渲染与 CF 中间件写入初始 HTML
 *
 * 写法原则：把用户真正会搜的词前置（如"免费/在线/格式"），
 * 主关键词在最前，补充词用 " - " 分隔。
 *
 * 维护方式：新增工具未配置时，generate-page-meta.mjs 会在构建时自动追加
 * 草稿标题（meta.title + 不重复关键词）并打印清单 —— 建议润色成更贴近
 * 真实搜索词的写法；生成器只增不改，润色后的条目不会被覆盖。
 * 路由删除后残留的条目会有警告，确认后手动删掉即可。
 */
export default {
  '/timetran': '时间戳转换工具 - Unix时间戳在线转日期时间',
  '/md5': 'MD5在线加密工具 - 免费32位/16位MD5加密',
  '/json': 'JSON在线格式化 - JSON编辑器/压缩/转义校验',
  '/csv-json': 'CSV转JSON - CSV/TSV与JSON在线互转',
  '/json-yaml': 'JSON转YAML - JSON/YAML格式化对比转换',
  '/reg': '正则表达式测试 - 在线正则匹配与常用正则大全',
  '/reg-viz': '正则表达式可视化 - 图形化演示正则匹配过程',
  '/cron': 'Cron表达式生成器 - 在线定时任务表达式解析',
  '/unicode': 'Unicode转中文 - 中文与Unicode编码在线互转',
  '/wordcount': '在线字数统计 - 字数/字符数一键计算',
  '/ip': 'IP查询 - 本机IP地址与归属地查询',
  '/scaletran': '进制转换 - 2/8/10/16/62进制在线互转',
  '/signimage': '在线图片编辑 - 裁剪/标注/滤镜/加文字',
  '/randompassword': '随机密码生成器 - 免费在线批量生成强密码',
  '/urlencode': 'URL编码解码 - URL在线编码/解密转换',
  '/ascii': 'ASCII码表 - 完整ASCII对照表在线查询',
  '/uuid': 'UUID生成器 - 在线批量生成UUID/GUID',
  '/barrage': '手持弹幕 - 手机滚动弹幕应援工具',
  '/palettes': '色板 - 配色色板与颜色快速选取',
  '/unit': '单位转换 - 长度/面积/重量/温度在线换算',
  '/arithmetic-practice': '小学加减法练习 - 自动出题口算训练',
  '/countdown-timer': '在线倒计时器 - 倒计时/正计时/定时提醒',
  '/pomodoro-timer': '番茄钟 - 番茄工作法在线专注计时',
  '/qrcode': '二维码生成器 - 免费在线制作二维码',
  '/qrcode-scan': '二维码识别 - 在线扫描/读取二维码内容',
  '/filesize': '文件大小转换 - KB/MB/GB/TB在线换算',
  '/decision': '帮我决定 - 选择困难症随机决定神器',
  '/morse': '摩斯电码 - 摩尔斯电码在线翻译转换',
  '/physics': '物理公式查询 - 高中/大学物理公式大全',
  '/math': '数学公式查询 - 代数/几何/微积分公式大全',
  '/random': '随机数生成器 - 在线批量生成随机数字',
  '/numbertochinese': '数字转大写 - 金额数字转中文大写在线',
  '/diff': '文本对比 - 在线文本/代码差异比对工具',
  '/stringclean': '字符串去空格 - 去除首尾/多余空格',
  '/markdown': 'Markdown编辑器 - 在线写作实时预览导出',
  '/texttoimg': '文本转图片 - 文字生成长图/推广图',
  '/line-art': '图片转线稿 - 照片一键生成铅笔线稿',
  '/webinfo': '网站Favicon获取 - 获取网站logo/标题/描述',
  '/bar': '柱状图在线制作 - 免费生成柱状图表',
  '/line': '折线图在线制作 - 免费生成折线图表',
  '/pie': '饼图在线制作 - 免费生成饼图图表',
  '/scatter': '散点图在线制作 - 免费生成散点图表',
  '/coin': '抛硬币 - 在线模拟抛硬币正反面',
  '/dice': '掷骰子 - 在线投骰子/自定义骰子',
  '/textremoveduplicate': '文本去重 - 在线去除重复行保留唯一值',
  '/imgcut': '图片切割 - 九宫格/四宫格在线切图',
  '/img-puzzle': '图片拼图 - 九宫格/心形拼图模板制作',
  '/httpstatuscode': 'HTTP状态码大全 - 含义解释与排查查询',
  '/jwt': 'JWT解析 - JSON Web Token在线解码',
  '/notes': '在线笔记 - 云端备忘录随时记录',
  '/confession-wall': '匿名告白墙 - 在线留言树洞互动墙',
  '/htmlentity': 'HTML实体转义 - 在线转义/反转义工具',
  '/colorpicker': '颜色选择器 - 在线取色/颜色代码查询',
  '/asciiwordpic': 'ASCII艺术字生成器 - 字形画在线制作',
  '/imagetobase64': '图片转Base64 - 编码解码在线互转',
  '/jsforamt': 'JS格式化 - JavaScript代码格式化/压缩',
  '/htmlformat': 'HTML格式化 - HTML/XML代码美化压缩',
  '/cssformat': 'CSS格式化 - CSS代码美化/压缩',
  '/textedit': '在线文本编辑 - 富文本编辑获取HTML',
  '/word-frequency': '词频统计 - 中英文分词频率分析工具',
  '/text-crypto': '文本加密解密 - AES-GCM在线加密工具',
  '/zodiac-fortune': '星座运势 - 今日/本周/本月运势查询',
  '/bagua-fortune': '命理八卦 - 五行生肖吉位在线查询',
  '/ai-text-to-video': 'AI文生视频 - 文本一键生成短视频',
  '/ai-image-edit': 'AI图片编辑 - AI修图/超分辨率放大',
  '/ai-image-edit/history': 'AI生成历史 - 我的AI图片生成记录',
  '/ai-media-works': 'AI媒体作品廊 - AI图片视频作品展示',
  '/my-ai-creations': '我的AI创作 - 私有AI作品画廊',
  '/ai-outfit': 'AI穿搭 - 虚拟试衣智能搭配建议',
  '/ai-outfit/history': 'AI穿搭历史 - 我的搭配生成记录',
  '/flashcards': '闪卡记忆 - 间隔重复复习工具',
  '/ai-text-to-speech': '文本转语音 - AI语音合成在线朗读',
  '/about': '关于本站 - 一方工具箱介绍',
  '/flip-clock': '翻页时钟 - 全屏翻页动画桌面时钟',
  '/led-display': 'LED弹屏 - LED滚动字幕走马灯工具',
  '/snake': '贪吃蛇小游戏 - 经典贪吃蛇在线玩',
  '/memory': '记忆翻牌 - 记忆力训练配对游戏',
  '/tetris': '俄罗斯方块 - 经典俄罗斯方块在线玩',
  '/whackamole': '打地鼠 - 反应力训练小游戏',
  '/game2048': '2048小游戏 - 经典2048在线玩',
  '/minesweeper': '扫雷游戏 - 经典扫雷在线玩',
  '/puzzle': '数字华容道 - 滑块拼图益智游戏',
  '/sudoku': '数独游戏 - 在线数独含解题提示',
  '/ai-gomoku': 'AI五子棋 - 人机对战在线五子棋',
  '/tic-tac-toe': '井字棋 - 双人/AI对战圈叉棋',
  '/gomoku-online': '双人五子棋 - 在线联机对战',
  '/aihub': 'AI工具导航 - 精选AI网站大全',
  '/ai-variable-name': 'AI变量命名 - 智能起编程变量名',
  '/ai-name': 'AI起名 - 智能中文姓名/宝宝取名',
  '/postman': '在线接口调试 - HTTP请求测试工具',
  '/urlparams': 'URL参数解析 - query参数解析/构造',
  '/naming-case': '命名风格转换 - camelCase/snake_case互转',
  '/hash': '哈希计算 - SHA256/HMAC在线校验',
  '/cookie': 'Cookie解析 - Set-Cookie在线解析/构造',
  '/short-link': '短链接生成 - 网址缩短/自定义短链',
  '/letter-writer': '在线写信 - 精美信件/情书生成分享',
  '/ai-translate': 'AI翻译 - 多语言智能在线翻译',
  '/ai-elementary-essay': 'AI作文 - 小学生作文生成器',
  '/ai-daily-motivation': 'AI鸡汤文 - 每日励志语录生成',
  '/good-sites': '好物网站导航 - 优质实用网站大全',
  '/ai-chat': 'AI对话 - 智能AI聊天助手在线',
  '/ai-interview': 'AI模拟面试 - 技术/产品面试练习',
  '/image-compress': '图片压缩 - 在线压缩图片大小',
  '/radiation-sample': '辐射量参考 - 常见物品辐射水平对比',
  '/guess-number': '猜数字 - 猜数字益智小游戏',
  '/number-memory': '数字记忆 - 瞬时记忆力训练游戏',
  '/math-equation-3d': '3D数学方程 - 三维方程可视化绘图',
  '/algorithm-visualization': '算法可视化 - 排序/查找算法动态演示',
  '/hundred-billion': '假如你有100亿 - 富翁模拟购物体验',
  '/ai-prompt': 'AI提示词库 - 精选Prompt模板大全',
  '/pdf-to-image': 'PDF转图片 - 在线转PNG/JPG高清',
  '/pdf-editor': 'PDF页眉页脚 - 在线添加/编辑PDF页码',
  '/me/credits': '积分与存储空间 - 我的积分明细流水',
  '/me/recharge': '积分充值 - 积分套餐与兑换码',
  '/mysql-to-go': 'MySQL转Go结构体 - DDL在线生成Model',
  '/mongo-to-sqlite': 'MongoDB转SQLite - JSON转SQL语句',
  '/base64': 'Base64编码解码 - 在线Base64互转工具',
  '/resume': '在线简历 - 简历制作与管理',
  '/company-compare': '公司对比 - 薪资福利/加班情况对比',
  '/minimum-wage': '最低工资标准 - 各省最低工资查询',
  '/phone-directory': '常用电话号码 - 公益/客服电话大全',
  '/travel-map': '旅游地图 - 路线规划/露营地标注',
  '/travel-map/plaza': '地图广场 - 旅游路线分享社区',
  '/music-playlist': '音乐播放列表 - 在线歌单管理与分享',
  '/qa': 'QA问答页制作 - 自定义FAQ页面生成',
  '/skill-poster': '闲鱼海报 - 技能海报在线制作',
  '/land-area': '土地亩数计算 - 平方米/亩/公顷换算',
  '/backend-docs': '后端开发文档 - Go/Redis/Nginx笔记',
  '/password-manager': '密码管理器 - AES加密在线密码本',
  '/temp-chat': '临时聊天室 - 匿名阅后即焚在线聊天',
  '/wechat-format': '公众号排版 - Markdown转微信格式',
  '/chinese-name': '随机人名生成 - 中文姓名/测试数据',
  '/video-to-gif': '视频转GIF - 在线视频转动图',
  '/id-photo': '证件照制作 - 一寸/二寸证件照裁剪',
  '/old-photo-caption': '老照片加字 - 经典留影题字生成',
  '/img-convert': '图片格式转换 - PNG/JPG在线互转',
  '/img-watermark': '图片加水印 - 文字水印在线制作',
  '/video-parser': '视频解析 - 在线VIP视频解析播放',
  '/weight-tracker': '体重记录 - BMI计算/体重曲线管理',
  '/height-tracker': '身高记录 - 儿童身高曲线管理',
  '/salary-tracker': '工资记录 - 薪资变化曲线追踪',
  '/fixed-expenses': '固定开销管理 - 每月订阅/账单记录',
  '/price-comparison': '物品比价 - 全网价格对比计算',
  '/shopping-list': '购物清单 - 在线买菜/采购清单',
  '/food-log': '饮食记录 - 今日三餐/卡路里管理',
  '/calculator': '在线计算器 - 科学计算器学生必备',
  '/compound-interest': '复利计算器 - 定投/年化收益计算',
  '/code-image': '代码转图片 - 高亮代码截图生成',
  '/doodle-pad': '在线画板 - 涂鸦画图白板工具',
  '/logic-training': '逻辑思维训练 - 推理题/智力题练习',
  '/mao-quotes': '毛选名句卡片 - 经典语录图片生成',
  '/bookmarks': '收藏夹 - 网页书签/稍后读管理',
  '/mock-data': 'Mock数据生成 - 接口测试假数据',
  '/season-scenery': '四季景色 - 全国景点四季风光对比',
  '/oss-manager': '阿里云OSS管理 - STS凭证/在线编辑',
  '/life-trajectory': '人生轨迹 - 轻量生活心情记录',
  '/retirement-countdown': '退休倒计时 - 法定退休年龄计算',
  '/generation-calculator': '辈分计算 - 亲戚称呼计算器',
  '/lights-out': '点灯游戏 - 经典Lights Out益智',
  '/make24': '24点 - 算24点四则运算游戏',
  '/image-color-count': '图片取色 - 颜色数量统计/色板提取',
  '/world-records': '世界之最 - 自然/地理/科技世界纪录大全',
}
