#!/usr/bin/env node
/**
 * 构建时自动生成 public/sitemap.xml，数据源是 functions/_page-meta.js
 * （generate-page-meta.mjs 从 router.ts 生成的可收录路由表，含 SKIP_PATHS 过滤），
 * 外加首页 —— 保证 sitemap 与页面 meta 永远同源，新增工具自动收录，
 * 不再出现「164 个工具 sitemap 只列 74 个」的滞后。
 *
 * lastmod 保留策略（避免每次构建都改文件产生 git 噪声）：
 *   - 已收录且 URL 集合没变 → 原样保留旧 lastmod，整个文件不重写
 *   - 新增 URL → lastmod = 本次构建日期
 *   - 已删除路由 → 从 sitemap 移除
 *
 * 运行时机：pnpm prebuild:pro（紧跟 gen:page-meta 之后，读最新的 _page-meta.js）；
 * 手动 node scripts/generate-sitemap.mjs 也可以。
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import PAGE_META, { siteOrigin } from '../functions/_page-meta.js'

const root = process.cwd()
const outFile = path.join(root, 'public', 'sitemap.xml')

if (!PAGE_META || Object.keys(PAGE_META).length === 0) {
  console.error('[gen:sitemap] functions/_page-meta.js 为空，先跑 pnpm gen:page-meta')
  process.exit(1)
}

// 本地日期（非 UTC），与 deploy 日志的 formatLocalTime 口径一致
function formatLocalDate(d) {
  const pad = (n) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
}

// ---- sitemap 条目 ----
// / 首页 daily 高权重；/about 低频；工具页 weekly —— Google 忽略
// changefreq/priority，这里只是给其他搜索引擎一个参考值
const entries = [
  { loc: `${siteOrigin}/`, changefreq: 'daily', priority: '1.0' },
  ...Object.keys(PAGE_META)
    .sort()
    .map((p) => ({
      loc: `${siteOrigin}${p}`,
      changefreq: p === '/about' ? 'monthly' : 'weekly',
      priority: p === '/about' ? '0.3' : '0.6',
    })),
]

// ---- 读取现有 sitemap 的 loc → lastmod ----
const prevLastmod = new Map()
if (existsSync(outFile)) {
  const xml = readFileSync(outFile, 'utf-8')
  for (const m of xml.matchAll(/<loc>([^<]+)<\/loc>[\s\S]*?<lastmod>([^<]+)<\/lastmod>/g)) {
    prevLastmod.set(m[1].trim(), m[2].trim())
  }
}

const today = formatLocalDate(new Date())

// URL 集合与现有完全一致时直接跳过，不动文件（零 git 噪声）
const prevLocs = [...prevLastmod.keys()].sort()
const nextLocs = entries.map((e) => e.loc).sort()
const unchanged =
  prevLocs.length === nextLocs.length && prevLocs.every((loc, i) => loc === nextLocs[i])
if (unchanged) {
  console.log(`[gen:sitemap] ${entries.length} 条 URL 与现有 sitemap 一致，跳过重写`)
  process.exit(0)
}

const added = entries.filter((e) => !prevLastmod.has(e.loc))
const removed = [...prevLastmod.keys()].filter((loc) => !nextLocs.includes(loc))

const lines = entries.map((e) => {
  // 新页面用构建日，老页面保留原 lastmod（Google 会拿它判断抓取频率，乱跳日期反而有害）
  const lastmod = prevLastmod.get(e.loc) || `${today}T00:00:00+00:00`
  return `  <url><loc>${e.loc}</loc><changefreq>${e.changefreq}</changefreq><priority>${e.priority}</priority><lastmod>${lastmod}</lastmod></url>`
})

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED by scripts/generate-sitemap.mjs —— 请勿手改 -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${lines.join('\n')}
</urlset>
`

writeFileSync(outFile, xml, 'utf-8')
console.log(
  `[gen:sitemap] ${entries.length} 条 URL → public/sitemap.xml` +
    (added.length ? `（新增 ${added.length}：${added.slice(0, 5).map((e) => e.loc).join(' ')}${added.length > 5 ? ' …' : ''}）` : '') +
    (removed.length ? `（移除 ${removed.length}：${removed.slice(0, 5).join(' ')}${removed.length > 5 ? ' …' : ''}）` : ''),
)
