name: 定时执行tool-web的生成图片任务

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: 请求 Cloudflare Pages Function
        run: |
          curl -X GET "https://tool.fologde.com/cron/test"
